const ComplianceData = (() => {
  const now = '2026-05-15T00:00:00.000Z';

  const frameworks = [
    {id:'iso27001-2022',name:'ISO/IEC 27001:2022',shortName:'ISO 27001',version:'2022',type:'ISMS',jurisdiction:'International',description:'Information security management system readiness support for scope, risk, governance, controls and evidence.',sourceNote:'Alpha summaries are original assessment support text, not official standard text.',alphaStatus:'initial',enabled:true,createdAt:now,updatedAt:now},
    {id:'nis2',name:'NIS2 Directive',shortName:'NIS2',version:'Article 21 focus',type:'Regulation',jurisdiction:'European Union',description:'Cybersecurity risk-management readiness support for governance, incident handling, continuity, supply chain and access control.',sourceNote:'Alpha summaries are original readiness support text and do not replace legal advice.',alphaStatus:'initial',enabled:true,createdAt:now,updatedAt:now},
    {id:'nist-csf-2',name:'NIST Cybersecurity Framework',shortName:'NIST CSF',version:'2.0',type:'Cybersecurity Framework',jurisdiction:'United States / International',description:'Govern, Identify, Protect, Detect, Respond and Recover readiness support with cross-framework mapping.',sourceNote:'Mappings are assessment support references and should be reviewed before formal use.',alphaStatus:'initial',enabled:true,createdAt:now,updatedAt:now},
    {id:'cis-v8',name:'CIS Controls',shortName:'CIS',version:'v8',type:'Control Baseline',jurisdiction:'International',description:'Practical safeguard-oriented security baseline for enterprise security hygiene.',sourceNote:'Alpha control summaries are representative and not a full CIS catalogue.',alphaStatus:'initial',enabled:true,createdAt:now,updatedAt:now},
    {id:'mitre-attack',name:'MITRE ATT&CK',shortName:'MITRE ATT&CK',version:'Enterprise tactics alpha',type:'Threat Knowledge Base',jurisdiction:'International',description:'Detection and response coverage mapping for adversary tactics and SOC maturity.',sourceNote:'Used for detection coverage, not as a compliance standard.',alphaStatus:'initial',enabled:true,createdAt:now,updatedAt:now},
    {id:'hipaa-security-rule',name:'HIPAA Security Rule',shortName:'HIPAA',version:'Security Rule alpha',type:'Healthcare Security',jurisdiction:'United States',description:'Healthcare security readiness support for electronic protected health information environments.',sourceNote:'Alpha support text does not replace legal or regulatory advice.',alphaStatus:'initial',enabled:true,createdAt:now,updatedAt:now},
    {id:'nsm-grunnprinsipper',name:'NSM Grunnprinsipper for IKT-sikkerhet',shortName:'NSM',version:'Alpha baseline',type:'National Baseline',jurisdiction:'Norway',description:'Norwegian ICT security baseline readiness support for practical security measures.',sourceNote:'Alpha support text is representative and should be reviewed by qualified professionals.',alphaStatus:'initial',enabled:true,createdAt:now,updatedAt:now}
  ];

  const domainTitles = {
    'iso27001-2022':['ISMS Scope','Risk Management','Governance & Review','Annex A Organizational','Annex A Technological'],
    nis2:['Governance','Risk Management Measures','Incident Handling','Business Continuity','Supply Chain Security','Access Control'],
    'nist-csf-2':['Govern','Identify','Protect','Detect','Respond','Recover'],
    'cis-v8':['Asset Inventory','Data Protection','Secure Configuration','Access Control','Vulnerability Management','Logging & Response','Recovery'],
    'mitre-attack':['Initial Access','Execution','Persistence','Privilege Escalation','Defense Evasion','Credential Access','Discovery','Lateral Movement','Collection','Command and Control','Exfiltration','Impact'],
    'hipaa-security-rule':['Administrative Safeguards','Physical & Workforce Safeguards','Technical Safeguards','Incident & Contingency'],
    'nsm-grunnprinsipper':['Identify','Protect','Detect','Respond & Recover','Third-Party Security']
  };

  const domains = frameworks.flatMap(framework => domainTitles[framework.id].map((title,index) => ({
    id:`${framework.id}-domain-${index+1}`,
    frameworkId:framework.id,
    code:title.split(' ').map(word => word[0]).join('').slice(0,6).toUpperCase(),
    title,
    description:`${title} readiness area for ${framework.shortName}.`,
    sortOrder:index+1
  })));

  function domainId(frameworkId,title){return domains.find(domain => domain.frameworkId===frameworkId && domain.title===title)?.id}
  function control(id,frameworkId,domainTitle,controlCode,title,requirementSummary,evidenceExamples,tags,sortOrder,applicability='Recommended'){
    return {id,frameworkId,domainId:domainId(frameworkId,domainTitle),controlCode,title,requirementSummary,implementationGuidance:`Use interviews, configuration evidence and documented process review to assess ${title.toLowerCase()}.`,applicability,controlObjective:title,evidenceExamples,relatedThreats:tags.filter(tag => ['ransomware','credential-access','lateral-movement','impact'].includes(tag)),relatedAssets:tags.filter(tag => ['identity','endpoint','backup','cloud','logs','suppliers'].includes(tag)),tags,sortOrder};
  }

  const controls = [
    control('iso-scope','iso27001-2022','ISMS Scope','Clause 4','ISMS scope is defined','The organization defines the boundaries, interested parties and context for the information security management system.',['ISMS scope statement','Interested-party register','Business context notes'],['governance','scope'],1,'Required'),
    control('iso-risk-assessment','iso27001-2022','Risk Management','Clause 6.1.2','Information security risk assessment','Risk assessment criteria, process and repeatable evaluation of information security risks are maintained.',['Risk assessment methodology','Risk register','Risk acceptance records'],['risk-management','governance'],2,'Required'),
    control('iso-risk-treatment','iso27001-2022','Risk Management','Clause 6.1.3','Information security risk treatment','Risk treatment plans and control selections are documented and tracked.',['Risk treatment plan','Control selection rationale','Treatment status report'],['risk-management','roadmap'],3,'Required'),
    control('iso-soa','iso27001-2022','Risk Management','SoA','Statement of Applicability','Applicable controls, exclusions and implementation status are documented.',['Statement of Applicability','Control applicability rationale'],['governance','evidence'],4,'Required'),
    control('iso-management-review','iso27001-2022','Governance & Review','Clause 9.3','Management review','Management periodically reviews ISMS performance, issues, metrics and improvement actions.',['Management review minutes','Security KPI report','Action tracker'],['governance','metrics'],5,'Required'),
    control('iso-internal-audit','iso27001-2022','Governance & Review','Clause 9.2','Internal audit','Internal audit activity evaluates whether the ISMS is operating as intended.',['Internal audit plan','Audit report','Corrective action records'],['governance','audit'],6,'Required'),
    control('iso-a515','iso27001-2022','Annex A Organizational','A.5.15','Access control','Rules for access to information and systems are defined, approved and enforced.',['Access control policy','Conditional access configuration','Access review evidence'],['iam','access-control','identity','credential-access'],7,'Recommended'),
    control('iso-a516','iso27001-2022','Annex A Organizational','A.5.16','Identity management','Identities and authentication factors are managed across the lifecycle.',['Identity lifecycle procedure','MFA policy','Privileged user export'],['iam','mfa','identity','credential-access'],8,'Recommended'),
    control('iso-a524','iso27001-2022','Annex A Organizational','A.5.24','Incident management planning','Incident management responsibilities, escalation and procedures are planned.',['Incident response plan','Tabletop report','Escalation matrix'],['incident-response','legal-notification'],9,'Recommended'),
    control('iso-a88','iso27001-2022','Annex A Technological','A.8.8','Technical vulnerability management','Technical vulnerabilities are identified, prioritized and remediated.',['Vulnerability scan report','Patch SLA report','Exception register'],['vulnerability','endpoint'],10,'Recommended'),
    control('iso-a813','iso27001-2022','Annex A Technological','A.8.13','Information backup','Backups are protected and restore capability is tested.',['Backup policy','Restore test report','Immutable backup configuration'],['backup','recovery','ransomware','impact'],11,'Recommended'),
    control('iso-a815','iso27001-2022','Annex A Technological','A.8.15','Logging','Logs are collected, protected and reviewed for relevant systems.',['Logging policy','SIEM source list','Retention configuration'],['logging','detection','logs'],12,'Recommended'),
    control('iso-a816','iso27001-2022','Annex A Technological','A.8.16','Monitoring activities','Systems and networks are monitored to detect anomalous activity.',['Monitoring use cases','Alert review records','Tuning backlog'],['monitoring','detection','logs'],13,'Recommended'),

    control('nis2-governance','nis2','Governance','Art. 20/21','Governance accountability','Management accountability and oversight for cybersecurity risk are defined.',['Board reporting pack','Security ownership matrix','Risk committee minutes'],['governance','risk-management'],1,'Contextual'),
    control('nis2-risk-policies','nis2','Risk Management Measures','Art. 21','Risk analysis and security policies','Risk analysis and information system security policies guide protection measures.',['Risk register','Security policies','Control plan'],['risk-management','policy'],2,'Contextual'),
    control('nis2-incident-handling','nis2','Incident Handling','Art. 21','Incident handling','Incident handling processes support detection, response, escalation and lessons learned.',['Incident response plan','Incident tickets','Post-incident review'],['incident-response','legal-notification'],3,'Contextual'),
    control('nis2-continuity','nis2','Business Continuity','Art. 21','Business continuity and crisis management','Continuity, backup and crisis procedures support resilience during major incidents.',['BCP','Crisis plan','Restore test evidence'],['backup','recovery','business-critical','impact'],4,'Contextual'),
    control('nis2-supply-chain','nis2','Supply Chain Security','Art. 21','Supply chain security','Supplier security risks and contractual requirements are managed.',['Supplier inventory','Security clauses','Supplier review record'],['third-party','suppliers'],5,'Contextual'),
    control('nis2-secure-development','nis2','Risk Management Measures','Art. 21','Secure acquisition and maintenance','Security is considered in acquisition, development, maintenance and vulnerability handling.',['Change procedure','Secure development checklist','Vulnerability disclosure process'],['vulnerability','cloud'],6,'Contextual'),
    control('nis2-training','nis2','Governance','Art. 21','Cyber hygiene and training','Users and administrators receive security awareness and cyber hygiene support.',['Training report','Phishing exercise report','Admin training record'],['awareness','governance'],7,'Contextual'),
    control('nis2-encryption','nis2','Access Control','Art. 21','Cryptography and encryption','Cryptography and encryption are applied where needed to protect information.',['Encryption policy','Key management evidence','Configuration screenshot'],['data-security','cloud'],8,'Contextual'),
    control('nis2-access','nis2','Access Control','Art. 21','Access control and asset management','Access control, asset visibility and secure authentication are maintained.',['Asset inventory','Access review','MFA configuration'],['iam','mfa','asset-management','identity'],9,'Contextual'),
    control('nis2-notification','nis2','Incident Handling','Art. 23 readiness','Incident notification readiness','Notification responsibilities and timelines are understood and rehearsed.',['Notification procedure','Contact list','Exercise record'],['incident-response','legal-notification'],10,'Contextual'),

    control('nist-gv-oc','nist-csf-2','Govern','GV.OC','Organizational context','Mission, stakeholders and dependencies are understood for cybersecurity risk decisions.',['Business context notes','Critical service map'],['governance','scope'],1),
    control('nist-gv-rm','nist-csf-2','Govern','GV.RM','Risk management strategy','Cybersecurity risk appetite, strategy and accountability are defined.',['Risk strategy','Risk appetite statement'],['risk-management','governance'],2),
    control('nist-gv-rr','nist-csf-2','Govern','GV.RR','Roles and responsibilities','Roles, responsibilities and authorities for cybersecurity are established.',['RACI','Role descriptions'],['governance'],3),
    control('nist-id-am','nist-csf-2','Identify','ID.AM','Asset management','Assets, services, users and dependencies are inventoried and prioritized.',['Asset inventory','CMDB export','Cloud asset export'],['asset-management','cloud'],4),
    control('nist-pr-aa','nist-csf-2','Protect','PR.AA','Identity management, authentication and access control','Identities, credentials and access are managed and protected.',['MFA policy','Access reviews','Privileged group export'],['iam','mfa','identity'],5),
    control('nist-pr-ds','nist-csf-2','Protect','PR.DS','Data security','Data is protected according to business and regulatory needs.',['Data classification','Encryption evidence'],['data-security'],6),
    control('nist-pr-ps','nist-csf-2','Protect','PR.PS','Platform security','Platforms are securely configured and maintained.',['Secure baseline','Configuration export'],['endpoint','secure-configuration'],7),
    control('nist-de-cm','nist-csf-2','Detect','DE.CM','Continuous monitoring','Networks, identities, endpoints and cloud services are monitored.',['SIEM source list','Alert dashboard','EDR coverage'],['logging','detection','monitoring'],8),
    control('nist-rs-ma','nist-csf-2','Respond','RS.MA','Incident management','Incidents are managed through defined response processes.',['IR plan','Incident tickets'],['incident-response'],9),
    control('nist-rs-an','nist-csf-2','Respond','RS.AN','Incident analysis','Incidents are analyzed to understand impact, cause and required action.',['Investigation notes','Post-incident review'],['incident-response','detection'],10),
    control('nist-rs-co','nist-csf-2','Respond','RS.CO','Incident response reporting','Internal and external response communication is planned.',['Communication plan','Notification runbook'],['incident-response','legal-notification'],11),
    control('nist-rc-rp','nist-csf-2','Recover','RC.RP','Recovery plan execution','Recovery plans are executed, tested and improved.',['Recovery plan','Restore test report'],['backup','recovery'],12),

    control('cis-1','cis-v8','Asset Inventory','CIS 1','Inventory and control of enterprise assets','Enterprise assets are inventoried and controlled.',['Asset inventory','Network scan report'],['asset-management'],1),
    control('cis-2','cis-v8','Asset Inventory','CIS 2','Inventory and control of software assets','Software assets are inventoried and managed.',['Software inventory','SaaS register'],['asset-management','cloud'],2),
    control('cis-3','cis-v8','Data Protection','CIS 3','Data protection','Data is identified, protected and retained according to need.',['Data inventory','DLP policy'],['data-security'],3),
    control('cis-4','cis-v8','Secure Configuration','CIS 4','Secure configuration','Enterprise assets and software are securely configured.',['Configuration baseline','Hardening evidence'],['secure-configuration','endpoint'],4),
    control('cis-5','cis-v8','Access Control','CIS 5','Account management','Accounts are inventoried, managed and reviewed.',['Account export','Joiner mover leaver evidence'],['iam','identity'],5),
    control('cis-6','cis-v8','Access Control','CIS 6','Access control management','Access rights and authentication protections are enforced.',['Access review','MFA configuration'],['iam','mfa','credential-access'],6),
    control('cis-7','cis-v8','Vulnerability Management','CIS 7','Continuous vulnerability management','Vulnerabilities are found, prioritized and remediated.',['Scan report','Patch SLA dashboard'],['vulnerability'],7),
    control('cis-8','cis-v8','Logging & Response','CIS 8','Audit log management','Audit logs are collected, retained and reviewed.',['Log source list','SIEM retention settings'],['logging','detection'],8),
    control('cis-9','cis-v8','Logging & Response','CIS 9','Email and web browser protections','Email and browser protections reduce common initial access risks.',['Email security settings','Browser policy'],['initial-access'],9),
    control('cis-10','cis-v8','Logging & Response','CIS 10','Malware defenses','Malware and endpoint threats are prevented, detected and contained.',['EDR coverage','Malware policy'],['endpoint','detection'],10),
    control('cis-11','cis-v8','Recovery','CIS 11','Data recovery','Recovery processes and backups are maintained and tested.',['Backup report','Restore test report'],['backup','recovery','ransomware'],11),
    control('cis-17','cis-v8','Logging & Response','CIS 17','Incident response management','Incident response roles, plans and exercises are maintained.',['IR plan','Exercise report'],['incident-response'],12),

    ...domainTitles['mitre-attack'].map((title,index) => control(`mitre-${title.toLowerCase().replaceAll(' ','-')}`,'mitre-attack',title,`TA${String(index+1).padStart(4,'0')}`,title,`${title} detection and response coverage is assessed through relevant log sources, use cases, triage and playbooks.`,['Detection use case','Alert test result','Playbook','Tuning record'],['mitre','detection','logging',title.toLowerCase().replaceAll(' ','-')],index+1,'Contextual')),

    control('hipaa-risk','hipaa-security-rule','Administrative Safeguards','164.308(a)(1)','Security management process','Security risks to electronic protected health information are identified and managed.',['Risk analysis','Risk management plan'],['healthcare','risk-management'],1,'Contextual'),
    control('hipaa-responsibility','hipaa-security-rule','Administrative Safeguards','164.308(a)(2)','Assigned security responsibility','Security responsibility is assigned and understood.',['Role assignment','Security officer designation'],['healthcare','governance'],2,'Contextual'),
    control('hipaa-workforce','hipaa-security-rule','Physical & Workforce Safeguards','164.308(a)(3)','Workforce security','Workforce access is authorized and supervised.',['Access authorization records','Termination checklist'],['healthcare','iam'],3,'Contextual'),
    control('hipaa-access-mgmt','hipaa-security-rule','Administrative Safeguards','164.308(a)(4)','Information access management','Access to ePHI systems is managed according to role and need.',['Access policy','Access review'],['healthcare','iam'],4,'Contextual'),
    control('hipaa-training','hipaa-security-rule','Administrative Safeguards','164.308(a)(5)','Security awareness and training','Workforce security awareness and training are maintained.',['Training report','Awareness materials'],['healthcare','awareness'],5,'Contextual'),
    control('hipaa-incident','hipaa-security-rule','Incident & Contingency','164.308(a)(6)','Security incident procedures','Security incident procedures are documented and used.',['Incident procedure','Incident tickets'],['healthcare','incident-response'],6,'Contextual'),
    control('hipaa-contingency','hipaa-security-rule','Incident & Contingency','164.308(a)(7)','Contingency plan','Contingency and recovery plans support critical healthcare operations.',['Contingency plan','Restore test'],['healthcare','backup','recovery'],7,'Contextual'),
    control('hipaa-access','hipaa-security-rule','Technical Safeguards','164.312(a)','Access control','Technical access controls restrict access to ePHI.',['Access control configuration','MFA evidence'],['healthcare','iam','mfa'],8,'Contextual'),
    control('hipaa-audit','hipaa-security-rule','Technical Safeguards','164.312(b)','Audit controls','Audit controls record activity in systems that handle ePHI.',['Audit log settings','Log review evidence'],['healthcare','logging'],9,'Contextual'),
    control('hipaa-integrity','hipaa-security-rule','Technical Safeguards','164.312(c)','Integrity','ePHI integrity is protected from improper alteration or destruction.',['Integrity control evidence','Change log'],['healthcare','data-security'],10,'Contextual'),
    control('hipaa-auth','hipaa-security-rule','Technical Safeguards','164.312(d)','Person or entity authentication','Users and entities are authenticated before access to ePHI.',['Authentication policy','Identity provider settings'],['healthcare','iam'],11,'Contextual'),
    control('hipaa-transmission','hipaa-security-rule','Technical Safeguards','164.312(e)','Transmission security','ePHI transmission is protected against unauthorized access.',['TLS configuration','Encryption policy'],['healthcare','data-security'],12,'Contextual'),

    control('nsm-assets','nsm-grunnprinsipper','Identify','GP-ID-1','Identify and map assets','Assets, services and dependencies are identified and prioritized.',['Asset register','Service map'],['asset-management'],1,'Recommended'),
    control('nsm-protect','nsm-grunnprinsipper','Protect','GP-PR-1','Protect systems and services','Systems and services are protected through baseline security measures.',['Security baseline','Configuration evidence'],['secure-configuration','endpoint'],2,'Recommended'),
    control('nsm-detect','nsm-grunnprinsipper','Detect','GP-DE-1','Detect and handle security events','Security events are detected, triaged and handled.',['Log source list','Alert workflow'],['logging','detection'],3,'Recommended'),
    control('nsm-recover','nsm-grunnprinsipper','Respond & Recover','GP-RR-1','Recover after incidents','Recovery capabilities are planned and tested.',['Recovery plan','Restore test'],['backup','recovery'],4,'Recommended'),
    control('nsm-iam','nsm-grunnprinsipper','Protect','GP-PR-2','Manage identities and access','Identity and access rights are managed and reviewed.',['Access review','MFA setup'],['iam','mfa'],5,'Recommended'),
    control('nsm-vuln','nsm-grunnprinsipper','Protect','GP-PR-3','Vulnerability management','Known vulnerabilities are identified and remediated.',['Vulnerability report','Patch status'],['vulnerability'],6,'Recommended'),
    control('nsm-suppliers','nsm-grunnprinsipper','Third-Party Security','GP-TP-1','Supplier and third-party security','Supplier risks and dependencies are understood and managed.',['Supplier register','Contract security clauses'],['third-party','suppliers'],7,'Recommended')
  ];

  const questionDefinitions = [
    {id:'cq-governance-ownership',domain:'Governance',question:'Is security ownership formally defined at management level?',description:'Checks whether accountability for security decisions is clear.',whyItMatters:'Clear ownership prevents security decisions from getting stuck.',tags:['governance'],evidence:['Security ownership matrix','Management reporting pack']},
    {id:'cq-security-policies',domain:'Governance',question:'Are security policies approved, communicated and reviewed?',description:'Checks whether policies are current, approved and usable.',whyItMatters:'Policies must be usable, not just documents on a shelf.',tags:['governance','policy'],evidence:['Security policy','Review record']},
    {id:'cq-security-kpis',domain:'Governance',question:'Are security KPIs reported to management?',description:'Checks whether leadership receives decision-ready security metrics.',whyItMatters:'Management cannot steer what it cannot see.',tags:['governance','metrics'],evidence:['KPI dashboard','Management review minutes']},
    {id:'cq-risk-register',domain:'Risk Management',question:'Is there a maintained information security risk register?',description:'Checks whether risks are documented, reviewed and owned.',whyItMatters:'A risk register turns issues into accountable business decisions.',tags:['risk-management'],evidence:['Risk register','Risk methodology']},
    {id:'cq-risk-owners',domain:'Risk Management',question:'Are risks assigned to accountable owners?',description:'Checks whether risks have decision owners and treatment follow-up.',whyItMatters:'Risks without owners do not get remediated.',tags:['risk-management','governance'],evidence:['Risk owner list','Treatment tracker']},
    {id:'cq-asset-inventory',domain:'Asset Management',question:'Is there a complete inventory of critical assets?',description:'Checks whether critical systems, users, endpoints and cloud assets are known.',whyItMatters:'You cannot protect or patch assets you do not know exist.',tags:['asset-management'],evidence:['Asset inventory','CMDB export','Cloud asset export']},
    {id:'cq-internet-assets',domain:'Asset Management',question:'Are internet-facing assets identified and reviewed?',description:'Checks whether public exposure is visible and reviewed.',whyItMatters:'Public exposure drives attack likelihood.',tags:['asset-management','initial-access'],evidence:['External exposure scan','Asset review record']},
    {id:'cq-mfa-users',domain:'Identity & Access Management',question:'Is MFA enforced for all users?',description:'Checks whether user authentication is protected with MFA.',whyItMatters:'MFA reduces account takeover risk.',tags:['iam','mfa','identity'],evidence:['MFA policy','Identity provider report']},
    {id:'cq-mfa-privileged',domain:'Identity & Access Management',question:'Is MFA enforced for all privileged accounts?',description:'Checks whether privileged access paths require strong authentication.',whyItMatters:'Privileged accounts are high-value targets in ransomware and intrusion scenarios.',tags:['iam','mfa','identity','credential-access','business-critical'],evidence:['Privileged MFA policy','Admin account export','Conditional access configuration']},
    {id:'cq-admin-separation',domain:'Identity & Access Management',question:'Are admin accounts separated from standard user accounts?',description:'Checks whether administrative activities use separate accounts.',whyItMatters:'Separation reduces blast radius after phishing or endpoint compromise.',tags:['iam','credential-access'],evidence:['Admin account standard','Privileged group export']},
    {id:'cq-privileged-review',domain:'Identity & Access Management',question:'Are privileged groups reviewed regularly?',description:'Checks whether privileged access remains appropriate over time.',whyItMatters:'Regular reviews remove stale or excessive access.',tags:['iam','access-control'],evidence:['Access review evidence','Privileged group export']},
    {id:'cq-edr-coverage',domain:'Endpoint Security',question:'Is EDR deployed on all business-critical endpoints and servers?',description:'Checks endpoint detection and containment coverage.',whyItMatters:'EDR coverage is a core detection and containment layer.',tags:['endpoint','detection'],evidence:['EDR coverage report','Server inventory']},
    {id:'cq-local-admin',domain:'Endpoint Security',question:'Are local admin rights restricted?',description:'Checks whether endpoint privilege is limited.',whyItMatters:'Local admin rights increase malware and lateral movement risk.',tags:['endpoint','iam','lateral-movement'],evidence:['Local admin report','Endpoint policy']},
    {id:'cq-segmentation',domain:'Network Security',question:'Is network segmentation implemented for critical systems?',description:'Checks whether network architecture limits lateral movement.',whyItMatters:'Segmentation limits lateral movement.',tags:['network','lateral-movement'],evidence:['Network diagram','Firewall rules']},
    {id:'cq-m365-admin',domain:'Cloud / SaaS Security',question:'Are M365 admin roles reviewed and minimized?',description:'Checks privileged roles in key SaaS platforms.',whyItMatters:'Cloud admin roles are often abused after credential compromise.',tags:['cloud','iam','access-control'],evidence:['M365 role export','Role review record']},
    {id:'cq-cloud-logging',domain:'Cloud / SaaS Security',question:'Is audit logging enabled for critical cloud services?',description:'Checks cloud audit log availability.',whyItMatters:'Without logs, detection and investigation become weak.',tags:['cloud','logging','detection'],evidence:['Cloud audit log settings','SIEM ingestion evidence']},
    {id:'cq-vuln-scans',domain:'Vulnerability Management',question:'Are vulnerability scans performed regularly?',description:'Checks whether technical exposure is visible.',whyItMatters:'Regular scanning provides visibility into exploitable weaknesses.',tags:['vulnerability'],evidence:['Vulnerability scan report','Scanning schedule']},
    {id:'cq-critical-vulns',domain:'Vulnerability Management',question:'Are critical vulnerabilities tracked to closure by SLA?',description:'Checks whether critical vulnerabilities are remediated with accountability.',whyItMatters:'Critical exposure must be remediated with accountable timelines.',tags:['vulnerability','business-critical'],evidence:['Patch SLA dashboard','Exception register']},
    {id:'cq-central-logs',domain:'Logging & Detection',question:'Are critical identity, endpoint and network logs centrally collected?',description:'Checks whether detection and investigation logs are available.',whyItMatters:'Central logging is required for effective detection and investigation.',tags:['logging','detection','mitre'],evidence:['SIEM source list','Log retention configuration']},
    {id:'cq-alert-tuning',domain:'Logging & Detection',question:'Are false positives reviewed and tuned regularly?',description:'Checks detection quality and tuning discipline.',whyItMatters:'Noise reduces analyst trust and weakens response.',tags:['logging','detection','mitre'],evidence:['Tuning backlog','Alert quality review']},
    {id:'cq-ir-plan',domain:'Incident Response',question:'Is there a documented incident response plan?',description:'Checks whether response roles, escalation and procedures are documented.',whyItMatters:'A written plan reduces confusion during pressure.',tags:['incident-response','legal-notification'],evidence:['Incident response plan','Escalation matrix']},
    {id:'cq-ir-test',domain:'Incident Response',question:'Has the incident response plan been tested in the last 12 months?',description:'Checks whether the response plan has been rehearsed.',whyItMatters:'Untested plans often fail during real incidents.',tags:['incident-response','business-critical'],evidence:['Tabletop report','Exercise action list']},
    {id:'cq-backups-critical',domain:'Backup & Recovery',question:'Are all business-critical systems backed up?',description:'Checks whether critical systems have backup coverage.',whyItMatters:'Backups are a core ransomware recovery control.',tags:['backup','recovery','ransomware','business-critical'],evidence:['Backup coverage report','Critical system list']},
    {id:'cq-restore-test',domain:'Backup & Recovery',question:'Has a restore test been performed in the last 6-12 months?',description:'Checks whether restore capability is proven.',whyItMatters:'Backups have little value if restore capability is unproven.',tags:['backup','recovery','ransomware','impact','business-critical'],evidence:['Restore test report','RTO/RPO evidence']},
    {id:'cq-immutable-backups',domain:'Backup & Recovery',question:'Are backups immutable or offline protected?',description:'Checks whether backups are protected from attacker deletion or encryption.',whyItMatters:'Attackers often target backups before ransomware deployment.',tags:['backup','recovery','ransomware'],evidence:['Immutable backup configuration','Backup access review']},
    {id:'cq-supplier-inventory',domain:'Third-Party Risk',question:'Is there an inventory of critical suppliers?',description:'Checks supplier visibility and dependency awareness.',whyItMatters:'Supplier risk cannot be managed without visibility.',tags:['third-party','suppliers'],evidence:['Supplier inventory','Critical supplier list']},
    {id:'cq-supplier-contracts',domain:'Third-Party Risk',question:'Are security requirements included in supplier contracts?',description:'Checks whether supplier obligations are contractually defined.',whyItMatters:'Contracts should define minimum security and incident obligations.',tags:['third-party','suppliers'],evidence:['Contract template','Supplier security clauses']}
  ].map(q => ({...q,maturityGuidance:{score0:'No evidence of implementation.',score1:'Ad hoc or incomplete implementation.',score2:'Partially defined but inconsistently applied.',score3:'Defined and mostly implemented.',score4:'Implemented with evidence and review.',score5:'Optimized, measured and continuously improved.'},defaultEvidenceRequirements:q.evidence,createdAt:now,updatedAt:now}));

  function mapByTags(question,controlItem){
    return question.tags.some(tag => controlItem.tags.includes(tag));
  }

  const mappings = questionDefinitions.flatMap(question => controls.filter(controlItem => mapByTags(question,controlItem)).map(controlItem => ({
    id:`map-${question.id}-${controlItem.id}`,
    questionId:question.id,
    frameworkControlId:controlItem.id,
    mappingStrength:question.tags.filter(tag => controlItem.tags.includes(tag)).length > 1 ? 'Direct' : 'Related',
    rationale:`The question and control share the ${question.tags.filter(tag => controlItem.tags.includes(tag)).join(', ')} assessment area.`
  })));

  const evidenceRequirements = controls.flatMap(controlItem => controlItem.evidenceExamples.map((example,index) => ({
    id:`ev-${controlItem.id}-${index+1}`,
    frameworkControlId:controlItem.id,
    title:example,
    description:`Evidence supporting ${controlItem.controlCode} ${controlItem.title}.`,
    evidenceType: example.includes('Report') || example.includes('report') ? 'Report' : example.includes('Export') || example.includes('export') ? 'Export' : example.includes('Log') || example.includes('log') ? 'Log' : example.includes('Configuration') || example.includes('configuration') || example.includes('settings') ? 'Configuration' : example.includes('Policy') || example.includes('policy') ? 'Policy' : 'Other',
    requiredFor:[controlItem.frameworkId],
    priority: controlItem.tags.some(tag => ['business-critical','mfa','backup','incident-response','legal-notification'].includes(tag)) ? 'High' : 'Medium'
  })));

  return {frameworks,domains,controls,questionDefinitions,mappings,evidenceRequirements,disclaimer:'Framework content in this Alpha version is intended for workflow testing and assessment support. It should not be treated as a complete certification-grade control catalogue. Framework mappings should be reviewed by a qualified professional before formal audit or regulatory conclusions.'};
})();
